image: docker:latest

services:
  - docker:dind

variables:
  LATEST_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

before_script:
  - env
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker build -t $LATEST_TAG .
    - docker push $LATEST_TAG
