image: docker:latest

services:
  - docker:dind

variables:
  LATEST_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

before_script:
  - env
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker build -t $LATEST_TAG .
    - docker run --rm --entrypoint bash $LATEST_TAG -c "apk --no-cache add php7-xdebug && echo zend_extension=xdebug.so > /etc/php7/conf.d/xdebug.ini && cd /phpcs && composer install --no-ansi --no-interaction && vendor/bin/phpunit --colors=never --coverage-text --coverage-html=build/coverage"
    - docker push $LATEST_TAG
